apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodegroups.cluster.eks.amazonaws.com
spec:
  group: cluster.eks.amazonaws.com
  names:
    kind: NodeGroup
    plural: nodegroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            name:
              type: string
            version:
              type: string
          required:
          - name
          type: object
        status:
          properties:
            status:
              type: string
          required:
          - status
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
