version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.5
  aws-cli: circleci/aws-cli@0.1.6
jobs:
  tests:
    docker:
      # specify the version
      - image: circleci/golang:1.11
      # - image: circleci/golang:1.12
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/awslabs/aws-eks-cluster-controller
    environment:
      KUBEBUILDER_CONTROLPLANE_START_TIMEOUT: "60s"
      TESTFLAGS: -p 2
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.5/kubebuilder_1.0.5_linux_amd64.tar.gz
      - run: tar -zxvf kubebuilder_1.0.5_linux_amd64.tar.gz
      - run: mv kubebuilder_1.0.5_linux_amd64 kubebuilder && sudo mv kubebuilder /usr/local/
      - run: export PATH=$PATH:/usr/local/kubebuilder/bin
      - run: go get github.com/jstemmer/go-junit-report
      # specify any bash command here prefixed with `run: `
      - run: mkdir -p ${TEST_RESULTS}/go-test
      - run: gotestsum --junitfile ${TEST_RESULTS}/go-testresults.xml -- ${TESTFLAGS} ./pkg/... 
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results
  deploy:
    docker:
      # specify the version
      - image: circleci/python:3-stretch-browsers
    working_directory: /go/src/github.com/awslabs/aws-eks-cluster-controller
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-region: AWS_REGION
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.11.6/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
      - run: curl -LO https://github.com/kubernetes-sigs/kustomize/releases/download/v1.0.11/kustomize_1.0.11_linux_amd64 && chmod +x kustomize* && sudo mv kustomize_1.0.11_linux_amd64 /usr/local/bin/kustomize
      - checkout
      - run: IMG="$AWS_ECR_ACCOUNT_URL/aws-eks-cluster-contoller:$CIRCLE_SHA1" IAMROLEARN=$CONTROLER_ROLE_ARN make deploy
      

workflows:
  version: 2
  build_and_push:
    jobs:
      - tests
      - aws-ecr/build_and_push_image:
          region: $AWS_REGION
          account-url: $AWS_ECR_ACCOUNT_URL
          repo: aws-eks-cluster-controller
          tag: $CIRCLE_SHA1
          dockerfile: Dockerfile
          path: .
          requires:
            - tests
      - deploy:
          requires:
            - aws-ecr/build_and_push_image


